### ISSUE TITLE
Image filters inquiry

### ISSUE THREAD

**Issue by NetOperatorWibby** [siebewarmoeskerken/siebewarmoeskerken.com#1]
Hey man, used to follow your work back in the day and even purchased an Lightroom/Photoshop preset or two. Will you be uploading those or working on ones for Affinity Photo?

**Comment by siebewarmoeskerken** [comment]
Hey, 
Funny that you found me here :) I created this account only a couple of hours ago.
I'm not a Adobe or Affinity user, I'm not actively photographing at the moment. 

Svetlana on VK was kind enough to share some of the Photoshop actions ;) https://vk.com/wall285834395_125

**Comment by NetOperatorWibby** [comment]
Oh nice, haha!

Yeah, my wife shared a picture of something last night and the way it looked reminded me of the caramel action you had! So, I went on a search for your name and boom. Your website was *just* created.

Well, thanks for all the inspiration over the years!
